### ISSUE TITLE
GA4 support?

### ISSUE THREAD

**Issue by schlosser** [sanity-io/sanity-plugin-google-analytics#6]
Hello! this doesn't seem to be working anymore. When I set it up with a GA3 project, I get this error:

```
You have created a new client application that uses libraries for user authentication or 
authorization that will soon be deprecated. New clients must use the new libraries instead; 
existing clients must also migrate before these libraries are deprecated. See the 
[Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
```

**Comment by progone** [comment]
I've noticed the samething.  The GA: format is different which is causing problems

**Comment by jonabc** [comment]
:wave: @schlosser

I've been working on an update for this plugin for the past few days and become blocked trying to integrate Google's new Analytics Data API (GA4), as the older analytics APIs are now deprecated and EOL for many google analytics users. The new data and auth API's from Google have been pretty tough to work with and unfortunately don't integrate well with the Google charting library in use in this plugin. As far as I can tell there is no publicly available visualization package that works well with the Analytics Data API response format.

Until these issues can be resolved, I don't think this plugin is going to be very usable.

I'm going to close the issue because it doesn't seem like there is much to be done here right now, but please feel free to add comments if there's anything else you have questions about.
