### ISSUE TITLE
This plugin only works with an older version of Sanity Studio (v2), which is deprecated.

### ISSUE THREAD

**Issue by nmoliveira** [sanity-io/sanity-plugin-google-analytics#7]
The [Sanity plugins page](https://www.sanity.io/plugins/sanity-plugin-google-analytics) mentions "this plugin only works with an older version of Sanity Studio (v2), which is deprecated." Will there be an updated version of this plugin or is there any other alternative? How should we integrate Google Analytics with v3?

**Comment by jonabc** [comment]
:wave: @nmoliveira unfortunately there is more to making this plugin usable than updating only to Studio v3.  

I've been working on an update for the past few days and become blocked trying to integrate Google's new Analytics Data API, as the older analytics APIs are now deprecated and EOL for many google analytics users.  The new data and auth API's from Google have been pretty tough to work with and unfortunately don't integrate well with the Google charting library in use in this plugin.  As far as I can tell there is no publicly available visualization package that works well with the Analytics Data API response format.

The new google APIs are blocking being able to easily update and maintain this plugin, and it doesn't seem worthwhile to update the plugin for studio v3 until progress can be made towards data querying and visualization.  I don't know of another way to integrate Google Analytics into Studio v3, sorry.

I'm going to close the issue because it doesn't seem like there is much to be done here right now, but please feel free to add comments if there's anything else you have questions about.
